# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5a449d24b659f3724046a96a7e7ba2a5d2ccbcf245169e221e0d4f86e315a6670a87b9e51bc08070fdac27171913a004a1994bd74d86f3169d95a4e37d7dd9

test:
  secret_key_base: 85dec2748fa1e8fb79f1cb68bb5393fc4f69e2acfeb4c2ed23ca04cc4edf1f53dc56b94c78002b3354d25139810a89df72dce6a68b045c2f7ed091837e386fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
